// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjfsfojfeyznnddxfspx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqZnNmb2pmZXl6bm5kZHhmc3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTQ3MzgsImV4cCI6MjA2MzQ3MDczOH0._JUOTDixaxMLhVkKKmSP7h3DyXdTBo-dvfEnsacKe4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);